"""
Default constants for MOVA configuration.
These values are intended as centralized defaults to avoid magic numbers
scattered across the configuration module. They can be overridden by
environment variables or by future BaseSettings-based configuration.
"""

__all__ = [
    "DEFAULT_LOG_LEVEL", "DEFAULT_LOG_FILE",
    "DEFAULT_API_TIMEOUT", "DEFAULT_API_RETRIES", "DEFAULT_API_RATE_LIMIT",
    "DEFAULT_CACHE_ENABLED", "DEFAULT_CACHE_TTL", "DEFAULT_CACHE_DIR",
    "DEFAULT_ENCRYPTION_ENABLED", "DEFAULT_ENCRYPTION_KEY",
    "DEFAULT_MAX_CONCURRENT_REQUESTS", "DEFAULT_REQUEST_TIMEOUT",
    "DEFAULT_DEBUG_MODE", "DEFAULT_VERBOSE_OUTPUT",
    "DEFAULT_LANGUAGE", "DEFAULT_SUPPORTED_LANGUAGES",
    "DEFAULT_WEBHOOK_ENABLED", "DEFAULT_WEBHOOK_TIMEOUT", "DEFAULT_WEBHOOK_MAX_RETRIES", "DEFAULT_WEBHOOK_SECRET",
    "DEFAULT_ML_ENABLED", "DEFAULT_ML_MODELS_DIR", "DEFAULT_ML_CONFIDENCE_THRESHOLD", "DEFAULT_ML_BATCH_SIZE",
    "DEFAULT_ML_MAX_CONCURRENT_REQUESTS", "DEFAULT_ML_CACHE_PREDICTIONS", "DEFAULT_ML_AUTO_RETRAIN",
    "DEFAULT_ML_RETRAIN_INTERVAL", "DEFAULT_ML_MIN_SAMPLES",
]

# Logging
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_FILE = None  # Path to log file, if used

# API
DEFAULT_API_TIMEOUT = 30
DEFAULT_API_RETRIES = 3
DEFAULT_API_RATE_LIMIT = 100

# Caching
DEFAULT_CACHE_ENABLED = True
DEFAULT_CACHE_TTL = 3600
DEFAULT_CACHE_DIR = ".mova_cache"

# Security
DEFAULT_ENCRYPTION_ENABLED = False
DEFAULT_ENCRYPTION_KEY = None

# Performance
DEFAULT_MAX_CONCURRENT_REQUESTS = 10
DEFAULT_REQUEST_TIMEOUT = 30

# Development
DEFAULT_DEBUG_MODE = False
DEFAULT_VERBOSE_OUTPUT = False

# Language
DEFAULT_LANGUAGE = "en"
DEFAULT_SUPPORTED_LANGUAGES = ["en", "uk"]

# Webhook
DEFAULT_WEBHOOK_ENABLED = True
DEFAULT_WEBHOOK_TIMEOUT = 30
DEFAULT_WEBHOOK_MAX_RETRIES = 3
DEFAULT_WEBHOOK_SECRET = None

# ML / AI integration
DEFAULT_ML_ENABLED = True
DEFAULT_ML_MODELS_DIR = "models"
DEFAULT_ML_CONFIDENCE_THRESHOLD = 0.8
DEFAULT_ML_BATCH_SIZE = 32
DEFAULT_ML_MAX_CONCURRENT_REQUESTS = 10
DEFAULT_ML_CACHE_PREDICTIONS = True
DEFAULT_ML_AUTO_RETRAIN = False
DEFAULT_ML_RETRAIN_INTERVAL = "7d"
DEFAULT_ML_MIN_SAMPLES = 1000